# Generated by Django 2.2.7 on 2019-11-21 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('platos', models.ManyToManyField(through='rest.Asignacion', to='rest.Plato')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Menu'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Plato'),
        ),
    ]
